server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_demo?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
  profiles:
    #默认配置为dev,会在开发调试时跳过token 的校验，提高调试效率
    active: prod

