server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_demo?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
#    druid:
#      initialSize: 1
#      minIdle: 1
#      maxActive: 50
#      maxWait: 6000
#      timeBetweenEvictionRunsMillis: 6000
#      minEvictableIdleTimeMillis: 30000
#      testWhileIdle: true
#      testOnBorrow: true
#      testOnReturn: true
#      validationQuery: SELECT 1 from dual
#      connectionProperties: config.decrypt=false